export { default as TeacherDashboard } from './TeacherDashboard'
export { default as TeacherCourses } from '../Teacher/TeacherCourses'
export { default as TeacherHome } from '../Teacher/TeacherHome'
export { default as TeacherNotice } from '../Teacher/TeacherNotice'
export { default as TeacherCourseDetails } from '../Teacher/TeacherCourseDetails'
