export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  COURSES: '/courses',
  COURSE_DETAILS: '/courses/:courseId',
  MODULE_DETAILS: '/courses/:courseId/module/:moduleId',

  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: 'dashboard',
    COURSES: 'courses',
    COURSE_DETAILS: '/admin/courses/:courseId',
    MANAGE_TEACHER: '/admin/teachers',
    MANAGE_TEACHER_DETAILS: '/admin/teachers/:courseId',
    MANAGE_STUDENT: '/admin/students',
    MANAGE_STUDENT_DETAILS: '/admin/students/:courseId',
    MANAGE_USER: '/admin/users',
    MANAGE_USER_DETAILS: '/admin/users/:courseId',
    MODULE_DETAILS: '/admin/courses/:courseId/module/:moduleId',
    USERS: 'users',
  },
  USER: {
    ROOT: '/user',
    DASHBOARD: 'dashboard',
    COURSES: 'courses',
    COURSE_DETAILS: '/user/courses/:courseId',
    MODULE_DETAILS: '/user/courses/:courseId/module/:moduleId',
    NOTICES: 'notices',
    SETTINGS: 'settings',
    FAQ: 'faq',
  },
  TEACHER: {
    ROOT: '/teacher',
    DASHBOARD: 'dashboard',
    COURSES: 'courses',
    COURSE_DETAILS: '/teacher/courses/:courseId',
    MODULE_DETAILS: '/teacher/courses/:courseId/module/:moduleId',
    NOTICES: 'notices',
  },

  STUDENT: {
    ROOT: '/student',
    DASHBOARD: 'dashboard',
    COURSES: 'courses',
    COURSE_DETAILS: '/student/courses/:courseId',
    MODULE_DETAILS: '/student/courses/:courseId/module/:moduleId',
  },
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    CONFIRM_EMAIL: '/auth/confirm-email',
    VERIFY_OTP: '/api/auth/verify-otp',
  },
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
}
