export { default as Home } from './Home'
export { default as About } from './About'
export { default as Courses } from './Courses'
export { default as CourseDetails } from './CourseDetails'
export { default as StudentCourseDetails } from '../Student/StudentCourseDetails'
export { default as SetPasswordPage } from '../SetPasswordpage'
