name: '✨ Feature Request'
description: 'Suggest a new feature or improvement'
title: '[Feature] <title>'
labels: [Feature, Needs Triage]
body:
  - type: textarea
    attributes:
      label: 'Feature Description'
      description: 'A clear and concise description of the feature you want to request.'
    validations:
      required: true
