name: '⏺️Parent Task Request'
description: 'Suggest a new Issue or improvement'
title: '[Parent Task] <title>'
labels: [Parent Task, Needs Triage]
body:
  - type: textarea
    attributes:
      label: 'Parent Task Description'
      description: 'A clear and concise description of the issue you want to request.'
    validations:
      required: true and here si the subTask subissue: name: '🎭 SubTask Request'
description: 'Suggest a new Issue or improvement' please fix 
title: '[SubTask] <title>'
labels: [SubTask, Needs Triage]
body:
  - type: textarea
    attributes:
      label: 'SubTask Description'
      description: 'A clear and concise description of the issue you want to request.'
    validations:
      required: true
