name: '🎭 SubTask Request'
description: 'Suggest a new Issue or improvement'
title: '[SubTask] <title>'
labels: [SubTask, Needs Triage]
body:
  - type: textarea
    attributes:
      label: 'SubTask Description'
      description: 'A clear and concise description of the issue you want to request.'
    validations:
      required: true
