name: '🎭 SubTask Request'
description: 'Suggest a new subtask or improvement'
title: '[SubTask] <title>'
labels: [SubTask, Needs Triage]
body:
  - type: textarea
    attributes:
      label: 'SubTask Description'
      description: 'A clear and concise description of the subtask.'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Parent Issue'
      description: 'Provide the parent issue number in the format: `#1234`'
